theme = "base16_default_dark"

[editor]
rulers = [80]

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.soft-wrap]
enable = true
